---
version: "3.6"
services:

  postgres:
    container_name: FinPost
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER= "<***>"
      - POSTGRES_PASSWORD= "<***>"
      - POSTGRES_DB= "<***>"
    volumes:
      -  "<***>"/FinPost/db-data/:/var/lib/postgresql/data/
    command: -p  "<***>"
    ports:
      - " "<***>": "<***>""
  
  pgadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${adminEmail}
      PGADMIN_DEFAULT_PASSWORD: ${adminPassword}
      PGADMIN_LISTEN_PORT:  "<***>"
    user: '$UID:$GID'
    ports:
      -  "<***>": "<***>"
    volumes:
      - ~/DOCKER/FinPost/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  lowcoder_redis:
    container_name: lowcoder_redis
    image: redis
    ports:
      - "${REDPORT}:${REDPORT}"
    volumes:
      - ${MAIN_FOLDER}Redis/redis.conf:/redis.conf
    environment:
      - REDIS_PORT=${REDPORT}
    command: ["redis-server", "/redis.conf","--port ${REDPORT}"]

  lowcoder:
    container_name: lowcoder
    image: lowcoderorg/lowcoder-ce:2.4.0
    restart: unless-stopped
    environment: 
      LOWCODER_PUBLIC_URL:  "<***>"
      LOWCODER_REDIS_ENABLED: "true"
      LOWCODER_MONGODB_ENABLED: "true"
      LOWCODER_MONGODB_EXPOSED: "true"
      LOWCODER_API_SERVICE_ENABLED: "true"
      LOWCODER_NODE_SERVICE_ENABLED: "true"
      LOWCODER_FRONTEND_ENABLED: "true"
      # generic parameters
      LOWCODER_PUID:  "<***>"
      LOWCODER_PGID:  "<***>"
      # api-service parameters
      LOWCODER_MAX_ORGS_PER_USER: 100
      LOWCODER_MAX_MEMBERS_PER_ORG: 1000
      LOWCODER_MAX_GROUPS_PER_ORG: 100
      LOWCODER_MAX_APPS_PER_ORG: 1000
      LOWCODER_MAX_DEVELOPERS: 50
      LOWCODER_MONGODB_URL: "mongodb://localhost:27017/lowcoder?authSource=admin"
      LOWCODER_REDIS_URL: "redis://lowcoder_redis: "<***>""
      LOWCODER_EMAIL_SIGNUP_ENABLED: "true"
      LOWCODER_EMAIL_AUTH_ENABLED: "true"
      LOWCODER_CREATE_WORKSPACE_ON_SIGNUP: "true"
      LOWCODER_DB_ENCRYPTION_PASSWORD: ${lcdbep}
      LOWCODER_DB_ENCRYPTION_SALT: ${lcdbep}
      LOWCODER_CORS_DOMAINS: "*"
      #
      # API-KEY secret - should be a string of at least 32 random characters
      #    - on linux/mac, generate one eg. with: head /dev/urandom | head -c 30 | shasum -a 256
      #
      LOWCODER_API_KEY_SECRET: "<***>"
      # api and node service parameters
      LOWCODER_API_SERVICE_URL: "http://localhost:8080"
      LOWCODER_NODE_SERVICE_URL: "http://localhost:6060"
      # frontend parameters
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_WORKSPACE_MODE: SAAS
    ports:
      - "<***>:3000"
      - "<***>:3443"
      - "2100:27017"
    volumes:
      - ${MAIN_FOLDER}Lowcoder:/lowcoder-stacks
      - ${MAIN_FOLDER}Lowcoder/assets:/lowcoder/assets
